server:
  port: 8080
spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi_yupao
    username: root
    password: 23240905hsh
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
#  # SpringDoc 基本配置
#  springdoc:
#    swagger-ui:
#      path: /swagger-ui.html
#      tags-sorter: alpha
#      operations-sorter: alpha
#    api-docs:
#      path: /v3/api-docs
#    # 分组配置（可选，按包扫描接口）
#    group-configs:
#      - group: 'default'
#        paths-to-match: '/**'
#        packages-to-scan: com.hsh.backend.controller # 替换为你项目的 Controller 包路径

# Knife4j 增强配置
knife4j:
  enable: true
  setting:
    language: zh-CN